/**
 * Copyright © ${creationYear} ${authorFullName} (http://www.gerdi-project.de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.gerdiproject.harvest.etls.transformers;

import java.io.File;
import java.nio.charset.StandardCharsets;

import de.gerdiproject.harvest.${providerClassName}ContextListener;
import de.gerdiproject.harvest.application.ContextListener;
import de.gerdiproject.harvest.application.MainContextUtils;
import de.gerdiproject.harvest.etls.AbstractIteratorETL;
import de.gerdiproject.harvest.etls.${providerClassName}ETL;
import de.gerdiproject.harvest.etls.extractors.${providerClassName}VO;
import de.gerdiproject.harvest.utils.data.DiskIO;
import de.gerdiproject.harvest.utils.data.constants.DataOperationConstants;
import de.gerdiproject.harvest.utils.file.FileUtils;
import de.gerdiproject.json.GsonUtils;
import de.gerdiproject.json.datacite.DataCiteJson;

/**
 * This class provides Unit Tests for the {@linkplain ${providerClassName}Transformer}.
 *
 * @author ${authorFullName}
 */
public class ${providerClassName}TransformerTest extends AbstractIteratorTransformerTest<${providerClassName}VO, DataCiteJson>
{
    final DiskIO diskReader = new DiskIO(GsonUtils.createGerdiDocumentGsonBuilder().create(), StandardCharsets.UTF_8);

	// TODO if the transformer does not receive ${providerClassName}VOs, replace all occurrences in the unit tests accordingly

    @Override
    protected ContextListener getContextListener()
    {
        return new ${providerClassName}ContextListener();
    }


    @Override
    protected AbstractIteratorTransformer<${providerClassName}VO, DataCiteJson> setUpTestObjects()
    {
		// TODO check which http responses are processed by the extractor's init() function, and add mocked versions in
		// TODO the src\test\resources\de\gerdiproject\harvest\etls\transformers\${providerClassName}TransformerTest\mockedHttpRequests folder
		
        // copy mocked HTTP responses to the cache folder to drastically speed up the testing
        final File httpResourceFolder = getResource("mockedHttpResponses");
        final File httpCacheFolder = new File(
            MainContextUtils.getCacheDirectory(getClass()),
            DataOperationConstants.CACHE_FOLDER_PATH);

        FileUtils.copyFile(httpResourceFolder, httpCacheFolder);
        
        return super.setUpTestObjects();
    }


    @Override
    protected AbstractIteratorETL<${providerClassName}VO, DataCiteJson> getEtl()
    {
        return new ${providerClassName}ETL();
    }


    @Override
    protected ${providerClassName}VO getMockedInput()
    {
		// TODO add the src\test\resources\de\gerdiproject\harvest\etls\transformers\${providerClassName}TransformerTest\input.json
		// TODO if the input object is not json, adjust the file name accordingly
		
		// TODO hint: re-use the output generated by the ${providerClassName}ExtractorTest if it represents a complete object
        final File resource = getResource("input.json");
        return diskReader.getObject(resource, ${providerClassName}VO.class);
    }


    @Override
    protected DataCiteJson getExpectedOutput()
    {
		// TODO add the src\test\resources\de\gerdiproject\harvest\etls\transformers\${providerClassName}TransformerTest\output.json
        final File resource = getResource("output.json");
        return diskReader.getObject(resource, DataCiteJson.class);
    }
}
